.TH "includes Directory Reference" 3 "Fri May 5 2017" "G-2311-03-P3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBG\-2311\-03\-P3canal\&.h\fP"
.br
.RI "\fIModulo de funciones la ejecucion de comandos en el servidor IRC relacionados con el usuario\&. \fP"
.ti -1c
.RI "file \fBG\-2311\-03\-P3commands\&.h\fP"
.br
.RI "\fIModulo de funciones para el reconocimiento y ejecucion de comandos en el servidor IRC\&. \fP"
.ti -1c
.RI "file \fBG\-2311\-03\-P3server\&.h\fP"
.br
.RI "\fILibreria de funciones para la gestion del servidor IRC\&. \fP"
.ti -1c
.RI "file \fBG\-2311\-03\-P3user\&.h\fP"
.br
.RI "\fIModulo de funciones la ejecucion de comandos en el servidor IRC relacionados con el usuario\&. \fP"
.ti -1c
.RI "file \fBG\-2311\-03\-P3utilidadesTAD\&.h\fP"
.br
.RI "\fIModulo de funciones axuliares para el manejo de los TADs que gestionan canales y usuarios\&. \fP"
.ti -1c
.RI "file \fBlib\&.h\fP"
.br
.RI "\fILibreria de funciones para la creacion y uso de un servidor basado en IRC\&. Implementacion de funciones OpenSSL\&. \fP"
.in -1c
