.TH "conectar_canal_seguro__s_s_l" 3 "Fri May 5 2017" "G-2311-03-P3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
conectar_canal_seguro__s_s_l \- \&.() \fB\fP 
conectar_canal_seguro_SSL - Conectar a un canal seguro
.SH "SINOPSIS"
.PP
\fB#include\fP \fB\fBlib\&.h\fP\fP 
.br
\fBint\fP conectar_canal_seguro_SSL(SSL_CTX *contex, SSL **ssl, int socket); 
.SH "Descripcion"
.PP
Dado un contexto SSL y un descriptor de socket esta función se encargará de obtener un canal seguro SSL iniciando el proceso de handshake con el otro extremo\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcontex\fP : contexto SSL 
.br
\fIssl\fP : canal seguro ssl 
.br
\fIsocket\fP : descriptor de socket 
.RE
.PP
.SH "RETORNO"
.PP
\fBReturns:\fP
.RS 4
-1 en caso de error 
.RE
.PP
.SH "VER TAMBIEN"
.PP
.SH "AUTORES"
.PP
Iñaki Cadalso innaki.cadalso@estudiante.uam.es, Enrique Aracil enrique.aracil@estudiante.uam.es 
