.TH "includes/G-2311-03-P3utilidadesTAD.h" 3 "Fri May 5 2017" "G-2311-03-P3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/G-2311-03-P3utilidadesTAD.h \- Modulo de funciones axuliares para el manejo de los TADs que gestionan canales y usuarios\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsend_all_user\fP (char *command)"
.br
.ti -1c
.RI "int \fBset_away\fP (char *nick, char *reason)"
.br
.ti -1c
.RI "long \fBget_numero_nlientes_actuales\fP ()"
.br
.ti -1c
.RI "long \fBget_numero_canales\fP ()"
.br
.ti -1c
.RI "int * \fBget_sockets_usuarios\fP ()"
.br
.ti -1c
.RI "char ** \fBget_nick_usuarios\fP ()"
.br
.ti -1c
.RI "char * \fBget_usuarios_canal\fP (char *channel)"
.br
.ti -1c
.RI "char ** \fBget_lista_canales\fP ()"
.br
.ti -1c
.RI "int \fBgetsocket\fP (char *nick)"
.br
.ti -1c
.RI "void \fBset_nick\fP (char *nick, char **userNick)"
.br
.ti -1c
.RI "char * \fBis_away\fP (char *nick)"
.br
.ti -1c
.RI "long \fBget_num_usuarios_canal\fP (char *channel)"
.br
.ti -1c
.RI "int \fBenviar_datos\fP (int sock, char *command)"
.br
.ti -1c
.RI "int \fBset_ssl\fP (SSL *ssl)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Modulo de funciones axuliares para el manejo de los TADs que gestionan canales y usuarios\&. 


.PP
\fBAuthor:\fP
.RS 4
Iñaki Cadalso innaki.cadalso@estudiante.uam.es, Enrique Aracil enrique.aracil@estudiante.uam.es Grupo 2311 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
13-02-2017 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for G-2311-03-P3 from the source code\&.
