.TH "includes/G-2311-03-P3canal.h" 3 "Fri May 5 2017" "G-2311-03-P3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/G-2311-03-P3canal.h \- Modulo de funciones la ejecucion de comandos en el servidor IRC relacionados con el usuario\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBjoin\fP (char *string, int sock, char *userNick)"
.br
.ti -1c
.RI "void \fBnames\fP (char *string, int sock, char *userNick)"
.br
.ti -1c
.RI "void \fBpart\fP (char *string, int sock, char *userNick)"
.br
.ti -1c
.RI "void \fBkick\fP (char *string, int sock, char *userNick)"
.br
.ti -1c
.RI "void \fBtopic\fP (char *string, int sock, char *userNick)"
.br
.ti -1c
.RI "void \fBmode\fP (char *string, int sock, char *userNick)"
.br
.ti -1c
.RI "void \fBmsg_canal\fP (char *channel, char *userNick, char *msg)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Modulo de funciones la ejecucion de comandos en el servidor IRC relacionados con el usuario\&. 


.PP
\fBAuthor:\fP
.RS 4
Iñaki Cadalso innaki.cadalso@estudiante.uam.es, Enrique Aracil enrique.aracil@estudiante.uam.es Grupo 2311 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
13-02-2017 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for G-2311-03-P3 from the source code\&.
