.TH "includes/G-2311-03-P3server.h" 3 "Fri May 5 2017" "G-2311-03-P3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/G-2311-03-P3server.h \- Libreria de funciones para la gestion del servidor IRC\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTIEMPO\fP   30"
.br
.RI "\fItiempo maximo de alarma en segundos \fP"
.ti -1c
.RI "#define \fBMSTIEMPO\fP   30000"
.br
.RI "\fItiempo maximo de alarma en milisegundos \fP"
.ti -1c
.RI "#define \fBPORT\fP   6667"
.br
.RI "\fIpuerto de escucha del servidor \fP"
.ti -1c
.RI "#define \fBSTIEMPO\fP   30"
.br
.RI "\fItiempo maximo de alarma en segundos \fP"
.ti -1c
.RI "#define \fBMSTIEMPO\fP   30000"
.br
.RI "\fItiempo maximo de alarma en milisegundos \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBdeal_cliente\fP (void *sock)"
.br
.ti -1c
.RI "int \fBrecibir\fP (int sock, char **userNick)"
.br
.ti -1c
.RI "long \fBget_numero_clientes\fP ()"
.br
.ti -1c
.RI "void \fBseguridad_ssl\fP ()"
.br
.ti -1c
.RI "void \fBaceptar_conexion_ssl\fP (int client_sock)"
.br
.ti -1c
.RI "int \fBrecibir_datos\fP (int sock, char *command)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Libreria de funciones para la gestion del servidor IRC\&. 


.PP
\fBAuthor:\fP
.RS 4
Iñaki Cadalso innaki.cadalso@estudiante.uam.es, Enrique Aracil enrique.aracil@estudiante.uam.es Grupo 2311 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
13-02-2017 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for G-2311-03-P3 from the source code\&.
