.TH "get_lista_canales" 3 "Fri May 5 2017" "G-2311-03-P3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
get_lista_canales \- () \fB\fP 
get_lista_canales - Lista de canales en el servidor
.SH "SINOPSIS"
.PP
\fB#include\fP \fBG-2311-03-P1utilidadesTAD\&.h\fP 
.br
\fBchar\fP **get_lista_canales(); 
.SH "Descripcion"
.PP
Devuelve la lista de canales registrados en el servidor\&. 
.SH "RETORNO"
.PP
\fBReturns:\fP
.RS 4
char**: array de char con los nombres de los canales\&. 
.RE
.PP
.SH "VER TAMBIEN"
.PP
.SH "AUTORES"
.PP
Iñaki Cadalso innaki.cadalso@estudiante.uam.es, Enrique Aracil enrique.aracil@estudiante.uam.es 
