.TH "get_nick_usuarios" 3 "Fri May 5 2017" "G-2311-03-P3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
get_nick_usuarios \- () \fB\fP 
get_nick_usuarios - Nicks de los usuarios en el Servidor
.SH "SINOPSIS"
.PP
\fB#include\fP \fBG-2311-03-P1utilidadesTAD\&.h\fP 
.br
\fBchar\fP **get_nick_usuarios(); 
.SH "Descripcion"
.PP
Devuelve los nicks de los usuarios registrados en el servidor\&. 
.SH "RETORNO"
.PP
\fBReturns:\fP
.RS 4
char**: array de char con los nicks de usuarios\&. 
.RE
.PP
.SH "VER TAMBIEN"
.PP
.SH "AUTORES"
.PP
Iñaki Cadalso innaki.cadalso@estudiante.uam.es, Enrique Aracil enrique.aracil@estudiante.uam.es 
