.TH "get_numero_clientes" 3 "Fri May 5 2017" "G-2311-03-P3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
get_numero_clientes \- () \fB\fP 
get_numero_clientes\&. - Numero de clientes conectados en el Servidor
.SH "SINOPSIS"
.PP
\fB#include\fP \fBG-2311-03-P1server\&.h\fP 
.br
\fBlong\fP get_numero_clientes(); 
.SH "Descripcion"
.PP
Devuelve el número de clintes conectados actualmente al servidor\&. 
.SH "RETORNO"
.PP
\fBReturns:\fP
.RS 4
long: nClientes\&. 
.RE
.PP
.SH "VER TAMBIEN"
.PP
.SH "AUTORES"
.PP
Iñaki Cadalso innaki.cadalso@estudiante.uam.es, Enrique Aracil enrique.aracil@estudiante.uam.es 
