.TH "get_numero_canales" 3 "Fri May 5 2017" "G-2311-03-P3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
get_numero_canales \- () \fB\fP 
get_numero_canales\&. - Numero de canales en el servidor
.SH "SINOPSIS"
.PP
\fB#include\fP \fBG-2311-03-P1utilidadesTAD\&.h\fP 
.br
\fBlong\fP get_numero_canales(); 
.SH "Descripcion"
.PP
Devuelve el número de canales activos actualmente en el servidor\&. 
.SH "RETORNO"
.PP
\fBReturns:\fP
.RS 4
long: num, numero de canales en el servidor\&. 
.RE
.PP
.SH "VER TAMBIEN"
.PP
.SH "AUTORES"
.PP
Iñaki Cadalso innaki.cadalso@estudiante.uam.es, Enrique Aracil enrique.aracil@estudiante.uam.es 
