.TH "get_usuarios_canal" 3 "Fri May 5 2017" "G-2311-03-P3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
get_usuarios_canal \- () \fB\fP 
get_usuarios_canal - Nicks de los usuarios en Canal
.SH "SINOPSIS"
.PP
\fB#include\fP \fBG-2311-03-P1utilidadesTAD\&.h\fP 
.br
\fBchar\fP *get_usuarios_canal(char * channel); 
.SH "Descripcion"
.PP
Devuelve los nicks de los usuarios conectados a un canal\&. 
.PP
\fBParameters:\fP
.RS 4
\fIchannel\fP Nombre del canal a buscar\&. 
.RE
.PP
.SH "RETORNO"
.PP
\fBReturns:\fP
.RS 4
char**: array de char con los nicks de usuarios\&. 
.RE
.PP
.SH "VER TAMBIEN"
.PP
.SH "AUTORES"
.PP
Iñaki Cadalso innaki.cadalso@estudiante.uam.es, Enrique Aracil enrique.aracil@estudiante.uam.es 
