.TH "get_num_usuarios_canal" 3 "Fri May 5 2017" "G-2311-03-P3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
get_num_usuarios_canal \- () \fB\fP 
get_num_usuarios_canal - Numero de usuarios en un canal
.SH "SINOPSIS"
.PP
\fB#include\fP \fBG-2311-03-P1utilidadesTAD\&.h\fP 
.br
\fBlong\fP get_num_usuarios_canal(char *channel); 
.SH "Descripcion"
.PP
consulta el numero de usuarios en un canal\&. 
.PP
\fBParameters:\fP
.RS 4
\fIchannel\fP Nombre del canal\&. 
.RE
.PP
.SH "RETORNO"
.PP
\fBReturns:\fP
.RS 4
long: numero de usuarios del canal\&. 
.RE
.PP
.SH "VER TAMBIEN"
.PP
.SH "AUTORES"
.PP
Iñaki Cadalso innaki.cadalso@estudiante.uam.es, Enrique Aracil enrique.aracil@estudiante.uam.es 
