.TH "get_sockets_usuarios" 3 "Fri May 5 2017" "G-2311-03-P3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
get_sockets_usuarios \- () \fB\fP 
get_sockets_usuarios - Sockets de Conexion
.SH "SINOPSIS"
.PP
\fB#include\fP \fBG-2311-03-P1utilidadesTAD\&.h\fP 
.br
\fBint\fP *get_sockets_usuarios(); 
.SH "Descripcion"
.PP
Devuelve los sockets de todos los usuarios\&. 
.SH "RETORNO"
.PP
\fBReturns:\fP
.RS 4
int*: array de int con los sockets de todos los usuarios\&. 
.RE
.PP
.SH "VER TAMBIEN"
.PP
.SH "AUTORES"
.PP
Iñaki Cadalso innaki.cadalso@estudiante.uam.es, Enrique Aracil enrique.aracil@estudiante.uam.es 
