.TH "ini_server" 3 "Fri May 5 2017" "G-2311-03-P3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ini_server \- () \fB\fP 
ini_server - Inicializacion Servidor
.SH "SINOPSIS"
.PP
\fB#include\fP \fB\fBlib\&.h\fP\fP 
.br
\fBint\fP ini_server(int port); 
.SH "Descripcion"
.PP
Inicializa un socket y lo deja escuchando 
.PP
\fBParameters:\fP
.RS 4
\fIport\fP Puerto donde escucha el servidor\&. 
.RE
.PP
.SH "RETORNO"
.PP
\fBReturns:\fP
.RS 4
int: EXIT_SUCCESS si todo fue correcto, EXIT_FAILURE en caso de error\&. 
.RE
.PP
.SH "VER TAMBIEN"
.PP
.SH "AUTORES"
.PP
Iñaki Cadalso innaki.cadalso@estudiante.uam.es, Enrique Aracil enrique.aracil@estudiante.uam.es 
