.TH "inicializar_nivel__s_s_l" 3 "Fri May 5 2017" "G-2311-03-P3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inicializar_nivel__s_s_l \- () \fB\fP 
inicializar_nivel_SSL - Inicializacion SSL
.SH "SINOPSIS"
.PP
\fB#include\fP \fB\fBlib\&.h\fP\fP 
.br
\fBvoid\fP inicializar_nivel_SSL (); 
.SH "Descripcion"
.PP
Esta función se encargará de realizar todas las llamadas necesarias para que la aplicación pueda usar la capa segura SSL\&. 
.SH "RETORNO"
.PP
.SH "VER TAMBIEN"
.PP
.SH "AUTORES"
.PP
Iñaki Cadalso innaki.cadalso@estudiante.uam.es, Enrique Aracil enrique.aracil@estudiante.uam.es 
