.TH "is_away" 3 "Fri May 5 2017" "G-2311-03-P3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
is_away \- () \fB\fP 
is_away - Comprobacion ausente
.SH "SINOPSIS"
.PP
\fB#include\fP \fBG-2311-03-P1utilidadesTAD\&.h\fP 
.br
\fBchar*\fP is_away(char *nick) ; 
.SH "Descripcion"
.PP
consulta el mensaje away de un usuario\&. 
.PP
\fBParameters:\fP
.RS 4
\fInick\fP Nick del usuario\&. 
.RE
.PP
.SH "RETORNO"
.PP
\fBReturns:\fP
.RS 4
char*: mensaje de away\&. 
.RE
.PP
.SH "VER TAMBIEN"
.PP
.SH "AUTORES"
.PP
Iñaki Cadalso innaki.cadalso@estudiante.uam.es, Enrique Aracil enrique.aracil@estudiante.uam.es 
