.TH "includes/lib.h" 3 "Fri May 5 2017" "G-2311-03-P3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/lib.h \- Libreria de funciones para la creacion y uso de un servidor basado en IRC\&. Implementacion de funciones OpenSSL\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBUFFER_SIZE\fP   8192"
.br
.RI "\fItamaño maximo que puede tener un buffer\&. \fP"
.ti -1c
.RI "#define \fBMAX_CLIENTS\fP   100"
.br
.RI "\fInumero de clientes maximo que soporta el servidor\&. \fP"
.ti -1c
.RI "#define \fBMAX_MNS\fP   2000"
.br
.RI "\fInumero maximo de milisegundos\&. \fP"
.ti -1c
.RI "#define \fBNUM_BYTES\fP   8192"
.br
.RI "\fItamaño maximo de bytes\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBon_error\fP (int log, char *err)"
.br
.ti -1c
.RI "int \fBini_server\fP (int port)"
.br
.ti -1c
.RI "int \fBdaemonizar\fP (char *service)"
.br
.ti -1c
.RI "int \fBaccept_conex\fP (int sock)"
.br
.ti -1c
.RI "void \fBhost_Ip\fP (int sock, char **host, char **ip)"
.br
.ti -1c
.RI "void \fBinicializar_nivel_SSL\fP ()"
.br
.ti -1c
.RI "int \fBfijar_contexto_SSL\fP (SSL_CTX **contex, char *cert, char *certRoot)"
.br
.ti -1c
.RI "int \fBcanal_seguro\fP (SSL_CTX *contex, SSL **ssl, int socket)"
.br
.ti -1c
.RI "int \fBconectar_canal_seguro_SSL\fP (SSL_CTX *contex, SSL **ssl, int socket)"
.br
.ti -1c
.RI "int \fBaceptar_canal_seguro_SSL\fP (SSL_CTX *contex, SSL **ssl, int socket)"
.br
.ti -1c
.RI "int \fBevaluar_post_connectar_SSL\fP (SSL *ssl)"
.br
.ti -1c
.RI "int \fBenviar_datos_SSL\fP (SSL *ssl, const void *buf, int num)"
.br
.ti -1c
.RI "int \fBrecibir_datos_SSL\fP (SSL *ssl, void *buf, int num)"
.br
.ti -1c
.RI "void \fBcerrar_canal_SSL\fP (SSL_CTX *contex, SSL *ssl, int socke)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Libreria de funciones para la creacion y uso de un servidor basado en IRC\&. Implementacion de funciones OpenSSL\&. 


.PP
\fBAuthor:\fP
.RS 4
Iñaki Cadalso innaki.cadalso@estudiante.uam.es, Enrique Aracil enrique.aracil@estudiante.uam.es Grupo 2311 
.RE
.PP
\fBVersion:\fP
.RS 4
3\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
23-03-2017 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for G-2311-03-P3 from the source code\&.
