.TH "ping" 3 "Fri May 5 2017" "G-2311-03-P3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ping \- () \fB\fP 
ping - Conexion Ping-Pong
.PP
G-2311-03-P3
.SH "SINOPSIS"
.PP
\fB#include\fP \fBG-2311-03-P1commands\&.h\fP 
.br
\fBvoid\fP ping(char *string, int sock, char *userNick) 
.SH "Descripcion"
.PP
Responde el servidor a una peticion de ping con un pong al cliente
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP Cadena que contiene el comando NICK y su informacion\&. 
.br
\fIsock\fP Puerto en el que se encuentra el usuario\&. 
.br
\fIuserNick\fP nick que usa el usuario conectado en el server\&. 
.RE
.PP
.SH "RETORNO"
.PP
Retorno void 
.SH "VER TAMBIEN"
.PP
.SH "AUTORES"
.PP
Iñaki Cadalso innaki.cadalso@estudiante.uam.es, Enrique Aracil enrique.aracil@estudiante.uam.es 
