.TH "recibir_datos" 3 "Fri May 5 2017" "G-2311-03-P3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
recibir_datos \- () \fB\fP 
recibir_datos - Creacion canal SSL
.SH "SINOPSIS"
.PP
\fB#include\fP \fBG-2311-03-P1server\&.h\fP 
.br
\fBint\fP recibir_datos(int sock, char *command); 
.SH "Descripcion"
.PP
recibe los datos enviados por el socket dado\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsock\fP conexion de socket\&. 
.br
\fIcommand\fP datos recibidos\&. 
.RE
.PP
.SH "RETORNO"
.PP
\fBReturns:\fP
.RS 4
int: numero de bytes recibidos\&. 
.RE
.PP
.SH "VER TAMBIEN"
.PP
.SH "AUTORES"
.PP
Iñaki Cadalso innaki.cadalso@estudiante.uam.es, Enrique Aracil enrique.aracil@estudiante.uam.es 
