.TH "send_all_user" 3 "Fri May 5 2017" "G-2311-03-P3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
send_all_user \- () \fB\fP 
send_all_user\&. - Envia a todos los usuarios
.SH "SINOPSIS"
.PP
\fB#include\fP \fBG-2311-03-P1utilidadesTAD\&.h\fP 
.br
\fBvoid\fP send_all_user(char *command); 
.SH "Descripcion"
.PP
Envia el commando dado a todos los clietes conectados al servidor 
.SH "RETORNO"
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP
.SH "VER TAMBIEN"
.PP
.SH "AUTORES"
.PP
Iñaki Cadalso innaki.cadalso@estudiante.uam.es, Enrique Aracil enrique.aracil@estudiante.uam.es 
