.TH "set_away" 3 "Fri May 5 2017" "G-2311-03-P3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
set_away \- () \fB\fP 
set_away\&. - Setea el mensaje de ausente
.SH "SINOPSIS"
.PP
\fB#include\fP \fBG-2311-03-P1utilidadesTAD\&.h\fP 
.br
\fBint\fP set_away(char* nick,char * reason); 
.SH "Descripcion"
.PP
Asigna el mensaje de ausente dado al actual usuario en el servidor 
.SH "RETORNO"
.PP
\fBReturns:\fP
.RS 4
int: Menor de 0 en caso de ERROR\&. 
.RE
.PP
.SH "VER TAMBIEN"
.PP
.SH "AUTORES"
.PP
Iñaki Cadalso innaki.cadalso@estudiante.uam.es, Enrique Aracil enrique.aracil@estudiante.uam.es 
