.TH "set_ssl" 3 "Fri May 5 2017" "G-2311-03-P3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
set_ssl \- () \fB\fP 
set_ssl - Activa la seguridad SSL
.SH "SINOPSIS"
.PP
\fB#include\fP \fB\fBG-2311-03-P3utilidadesTAD\&.h\fP\fP 
.br
\fBint\fP set_ssl(SSL* ssl); 
.SH "Descripcion"
.PP
Activa la seguridad SSL en los envios\&. 
.PP
\fBParameters:\fP
.RS 4
\fIssl\fP canal de conexion seguro con SSL\&. 
.RE
.PP
.SH "RETORNO"
.PP
\fBReturns:\fP
.RS 4
int: menor que 1 en caso de fallo\&. 
.RE
.PP
.SH "VER TAMBIEN"
.PP
.SH "AUTORES"
.PP
Iñaki Cadalso innaki.cadalso@estudiante.uam.es, Enrique Aracil enrique.aracil@estudiante.uam.es 
