.TH "topic" 3 "Fri May 5 2017" "G-2311-03-P3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
topic \- () \fB\fP 
topic - Mensaje canal
.SH "SINOPSIS"
.PP
\fB#include\fP \fBG-2311-03-P1canal\&.h\fP 
.br
\fBvoid\fP topic(char *string, int sock, char *userNick) 
.SH "Descripcion"
.PP
Cambia el topic de un canal dado\&. Comprueba el nivel de proteccion del canal para el cambio por parte del dueño del canal\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP Cadena que contiene el comando TOPIC y su informacion\&. 
.br
\fIsock\fP Puerto en el que se encuentra el usuario\&. 
.br
\fIuserNick\fP nick que usa el usuario conectado en el server\&. 
.RE
.PP
.SH "RETORNO"
.PP
Retorno void 
.SH "VER TAMBIEN"
.PP
.SH "AUTORES"
.PP
Iñaki Cadalso innaki.cadalso@estudiante.uam.es, Enrique Aracil enrique.aracil@estudiante.uam.es 
